[package]
name = "mdm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.15.0"
colored = "2.0.0"
chrono = "0.4"
confy = "0.6.1"
serde = { version = "1.0.197", features = ["derive"]}
